version: "3.7"
services:
  mi-proyecto-microservicio:
    container_name: mi-proyecto-microservicio
    image: mi-proyecto-microservicio:v1
    build :
      context: .
    ports:
      - "9001"
    networks:
      - proyectos-app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=9001

  mi-proyecto-microservicio-2:
    container_name: mi-proyecto-microservicio-2
    image: mi-proyecto-microservicio:v1
    build :
      context: .
    ports:
      - "9001"
    networks:
      - proyectos-app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=9001


  mi-proyecto-microservicio-3:
    container_name: mi-proyecto-microservicio-3
    image: mi-proyecto-microservicio:v1
    build :
      context: .
    ports:
      - "9001"
    networks:
      - proyectos-app
    environment:
      - MONGODB_URI=${MONGODB_URI}
      - PORT=9001


  balanceador:
    container_name: balanceador
    image: balanceador:v1
    build :
      context: ./balanceador
    ports:
      - "9002:80"
    networks:
      - proyectos-app

networks:
  proyectos-app:
